# This is a comment
FROM ubuntu:16.04
COPY src /src223
MAINTAINER Docker Newbee <newbee@docker.com>
RUN apt-get update\
	&& apt-get -y install vim\
	&& apt-get -y install libc-dev\
	&& apt-get -y install gcc

